---
# handlers file for ansible-role-filebeat-postfix-bounce
- name: restart logstash
  service: 
    name: logstash
    state: restarted

- name: enable logstash
  service:
    name: logstash
    enabled: yes
